# Developing Sequential Artifical Neural Network Model

## STEP 1 installing Keras, Tensorflow and Theano

In [1]:
# packages
# Installing Theano
!pip install --upgrade theano
# Installing Tensorflow
!pip install  tensorflow
# Installing Keras
!pip install --upgrade keras

Requirement already up-to-date: theano in /home/jupyterlab/conda/lib/python3.6/site-packages (1.0.4)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /home/jupyterlab/conda/lib/python3.6/site-packages (from theano) (1.16.1)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from theano) (1.12.0)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in /home/jupyterlab/conda/lib/python3.6/site-packages (from theano) (1.1.0)
Requirement already satisfied: tensorflow in /home/jupyterlab/conda/lib/python3.6/site-packages (1.8.0)
Requirement already satisfied: wheel>=0.26 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (0.32.3)
Requirement already satisfied: gast>=0.2.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (0.2.2)
Requirement already satisfied: tensorboard<1.9.0,>=1.8.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (1.8.0)
Requirement already satisfied: absl-py>=0.1.6 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: protobuf>=3.4.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (3.6.1)
Requirement already satisfied: six>=1.10.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (1.12.0)
Requirement already satisfied: numpy>=1.13.3 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (1.16.1)
Requirement already satisfied: termcolor>=1.1.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (1.16.1)
Requirement already satisfied: astor>=0.6.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorflow) (0.7.1)
Requirement already satisfied: werkzeug>=0.11.10 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (0.14.1)
Requirement already satisfied: html5lib==0.9999999 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (0.9999999)
Requirement already satisfied: markdown>=2.6.8 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (3.0.1)
Requirement already satisfied: bleach==1.5.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (1.5.0)
Requirement already satisfied: setuptools in /home/jupyterlab/conda/lib/python3.6/site-packages (from protobuf>=3.4.0->tensorflow) (40.8.0)
Requirement already up-to-date: keras in /home/jupyterlab/conda/lib/python3.6/site-packages (2.2.4)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (1.0.7)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (1.16.1)
Requirement already satisfied, skipping upgrade: h5py in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (2.8.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (1.0.9)
Requirement already satisfied, skipping upgrade: pyyaml in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (3.13)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /home/jupyterlab/conda/lib/python3.6/site-packages (from keras) (1.12.0)

In [3]:
# Importing the libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
# Importing the database
dataset = pd.read_csv('nhiesincml.csv',index_col = 0)

## STEP 2 Verifying exploring again the needed variables

In [4]:
dataset.head()

,sex_of_head,age_group,age_of_head,reg_urb,main_language,main_sourceincome,tenure,urbrur_head,attain,apci,label_apci,ncons_exp,g01_food,income,cons_exp,apci_groups
0,2,3,35,2,5,1,3,4,3.0,23453.849609,3,1800.0,6681.848633,23453.849609,21653.849609,3
1,2,2,25,2,10,5,4,4,3.0,29355.007812,3,1800.0,10505.010742,29355.007812,27555.007812,3
2,1,4,51,2,5,1,1,3,2.0,91796.781250,4,2500.0,35028.773438,91796.781250,89296.773438,5
3,2,4,54,2,5,5,1,4,3.0,16954.039062,2,0.0,1756.040039,16954.039062,16954.039062,3
4,1,3,35,2,12,1,3,3,3.0,24646.001953,3,960.0,9542.000000,49292.003906,48332.000000,3

In [6]:
dataset.isnull().any()

sex_of_head          False
age_group            False
age_of_head          False
reg_urb              False
main_language        False
main_sourceincome    False
tenure               False
urbrur_head          False
attain               False
apci                 False
label_apci           False
ncons_exp            False
g01_food             False
income               False
cons_exp             False
apci_groups          False
dtype: bool

In [7]:
dataset.dtypes

sex_of_head            int64
age_group              int64
age_of_head            int64
reg_urb                int64
main_language          int64
main_sourceincome      int64
tenure                 int64
urbrur_head            int64
attain               float64
apci                 float64
label_apci             int64
ncons_exp            float64
g01_food             float64
income               float64
cons_exp             float64
apci_groups            int64
dtype: object

In [8]:
dataset.head()

,sex_of_head,age_group,age_of_head,reg_urb,main_language,main_sourceincome,tenure,urbrur_head,attain,apci,label_apci,ncons_exp,g01_food,income,cons_exp,apci_groups
0,2,3,35,2,5,1,3,4,3.0,23453.849609,3,1800.0,6681.848633,23453.849609,21653.849609,3
1,2,2,25,2,10,5,4,4,3.0,29355.007812,3,1800.0,10505.010742,29355.007812,27555.007812,3
2,1,4,51,2,5,1,1,3,2.0,91796.781250,4,2500.0,35028.773438,91796.781250,89296.773438,5
3,2,4,54,2,5,5,1,4,3.0,16954.039062,2,0.0,1756.040039,16954.039062,16954.039062,3
4,1,3,35,2,12,1,3,3,3.0,24646.001953,3,960.0,9542.000000,49292.003906,48332.000000,3

In [9]:
dataset.shape

(10090, 16)

In [10]:
print(dataset['main_language'].value_counts())

6     4610
5     1292
4     1272
3     1000
8      715
2      572
13     165
1      146
10     111
12     108
11      35
9       33
7       31
Name: main_language, dtype: int64

In [11]:
dataset = dataset.drop(['apci','reg_urb'], axis=1)

In [12]:
# convert attain to int
cols = ['attain','label_apci']
dataset[cols] = dataset[cols].applymap(np.int64)
dataset.head()

,sex_of_head,age_group,age_of_head,main_language,main_sourceincome,tenure,urbrur_head,attain,label_apci,ncons_exp,g01_food,income,cons_exp,apci_groups
0,2,3,35,5,1,3,4,3,3,1800.0,6681.848633,23453.849609,21653.849609,3
1,2,2,25,10,5,4,4,3,3,1800.0,10505.010742,29355.007812,27555.007812,3
2,1,4,51,5,1,1,3,2,4,2500.0,35028.773438,91796.781250,89296.773438,5
3,2,4,54,5,5,1,4,3,2,0.0,1756.040039,16954.039062,16954.039062,3
4,1,3,35,12,1,3,3,3,3,960.0,9542.000000,49292.003906,48332.000000,3

In [13]:
# move sex_of_head col after age_of_head
cols = list(dataset)
cols.insert(2, cols.pop(cols.index('sex_of_head')))
dataset = dataset[cols]
dataset.head()

,age_group,age_of_head,sex_of_head,main_language,main_sourceincome,tenure,urbrur_head,attain,label_apci,ncons_exp,g01_food,income,cons_exp,apci_groups
0,3,35,2,5,1,3,4,3,3,1800.0,6681.848633,23453.849609,21653.849609,3
1,2,25,2,10,5,4,4,3,3,1800.0,10505.010742,29355.007812,27555.007812,3
2,4,51,1,5,1,1,3,2,4,2500.0,35028.773438,91796.781250,89296.773438,5
3,4,54,2,5,5,1,4,3,2,0.0,1756.040039,16954.039062,16954.039062,3
4,3,35,1,12,1,3,3,3,3,960.0,9542.000000,49292.003906,48332.000000,3

## STEP 3 Engineering features

In [14]:
X = dataset.iloc[:, 0:14].values
Y = dataset.iloc[:, 13].values
X

array([[3.00000000e+00, 3.50000000e+01, 2.00000000e+00, ...,
        2.34538496e+04, 2.16538496e+04, 3.00000000e+00],
       [2.00000000e+00, 2.50000000e+01, 2.00000000e+00, ...,
        2.93550078e+04, 2.75550078e+04, 3.00000000e+00],
       [4.00000000e+00, 5.10000000e+01, 1.00000000e+00, ...,
        9.17967812e+04, 8.92967734e+04, 5.00000000e+00],
       ...,
       [5.00000000e+00, 5.50000000e+01, 2.00000000e+00, ...,
        5.50095938e+04, 5.48695938e+04, 3.00000000e+00],
       [6.00000000e+00, 7.30000000e+01, 2.00000000e+00, ...,
        7.08872734e+04, 7.05372812e+04, 4.00000000e+00],
       [6.00000000e+00, 7.50000000e+01, 1.00000000e+00, ...,
        2.62423320e+04, 2.59923340e+04, 3.00000000e+00]])

In [15]:
Y

array([3, 3, 5, ..., 3, 4, 3])

In [17]:
ds = pd.DataFrame({'AgeGroup':X[:,0],'AgeHead':X[:,1],'SexHead':X[:,2],'Mainlang':X[:,3],'Mainsinc':X[:,4],\
                   'Tenure':X[:,5],'Urbrur':X[:,6],'Attain':X[:,7],'apci_groups':X[:,13]})

In [18]:
ds.head()

,AgeGroup,AgeHead,SexHead,Mainlang,Mainsinc,Tenure,Urbrur,Attain,apci_groups
0,3.0,35.0,2.0,5.0,1.0,3.0,4.0,3.0,3.0
1,2.0,25.0,2.0,10.0,5.0,4.0,4.0,3.0,3.0
2,4.0,51.0,1.0,5.0,1.0,1.0,3.0,2.0,5.0
3,4.0,54.0,2.0,5.0,5.0,1.0,4.0,3.0,3.0
4,3.0,35.0,1.0,12.0,1.0,3.0,3.0,3.0,3.0

In [19]:
from sklearn.preprocessing import OneHotEncoder

AgeGroup_he = OneHotEncoder()
SexHead_he = OneHotEncoder()
Mainlang_he = OneHotEncoder()
Mainsinc_he = OneHotEncoder()
Tenure_he = OneHotEncoder()
Urbrur_he = OneHotEncoder()
Attain_he = OneHotEncoder()
apci_groups_he = OneHotEncoder()

AgeGroupn = AgeGroup_he.fit_transform(ds.AgeGroup.values.reshape(-1,1)).toarray()
SexHeadn = SexHead_he.fit_transform(ds.SexHead.values.reshape(-1,1)).toarray()
Mainlangn = Mainlang_he.fit_transform(ds.Mainlang.values.reshape(-1,1)).toarray()
Mainsincn = Mainsinc_he.fit_transform(ds.Mainsinc.values.reshape(-1,1)).toarray()
Tenuren = Tenure_he.fit_transform(ds.Tenure.values.reshape(-1,1)).toarray()
Urbrurn = Urbrur_he.fit_transform(ds.Urbrur.values.reshape(-1,1)).toarray()
Attainn = Attain_he.fit_transform(ds.Attain.values.reshape(-1,1)).toarray()
apci_groups = apci_groups_he.fit_transform(ds.apci_groups.values.reshape(-1,1)).toarray()

/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/jupyterlab/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

## STEP 4 Encoding variables

In [20]:
dfOneHot = pd.DataFrame(AgeGroupn, columns = ["AgeGroup_"+str(int(i)) for i in range(AgeGroupn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [21]:
dfOneHot = pd.DataFrame(SexHeadn, columns = ["SexHead_"+str(int(i)) for i in range(SexHeadn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [22]:
dfOneHot = pd.DataFrame(Mainlangn, columns = ["Mainlang_"+str(int(i)) for i in range(Mainlangn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [23]:
dfOneHot = pd.DataFrame(Mainsincn, columns = ["Mainsinc_"+str(int(i)) for i in range(Mainsincn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [24]:
dfOneHot = pd.DataFrame(Tenuren, columns = ["Tenure_"+str(int(i)) for i in range(Tenuren.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [25]:
dfOneHot = pd.DataFrame(Urbrurn, columns = ["Urbrur_"+str(int(i)) for i in range(Urbrurn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [26]:
dfOneHot = pd.DataFrame(Attainn, columns = ["Attain_"+str(int(i)) for i in range(Attainn.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [27]:
ds.head()

,AgeGroup,AgeHead,SexHead,Mainlang,Mainsinc,Tenure,Urbrur,Attain,apci_groups,AgeGroup_0,...,Urbrur_0,Urbrur_1,Urbrur_2,Urbrur_3,Attain_0,Attain_1,Attain_2,Attain_3,Attain_4,Attain_5
0,3.0,35.0,2.0,5.0,1.0,3.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2.0,25.0,2.0,10.0,5.0,4.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,4.0,51.0,1.0,5.0,1.0,1.0,3.0,2.0,5.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4.0,54.0,2.0,5.0,5.0,1.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,3.0,35.0,1.0,12.0,1.0,3.0,3.0,3.0,3.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [28]:
dfOneHot = pd.DataFrame(apci_groups, columns = ["apci_groups_"+str(int(i)) for i in range(apci_groups.shape[1])])
ds = pd.concat([ds, dfOneHot], axis=1)

In [29]:
ds.head()

,AgeGroup,AgeHead,SexHead,Mainlang,Mainsinc,Tenure,Urbrur,Attain,apci_groups,AgeGroup_0,...,Attain_3,Attain_4,Attain_5,apci_groups_0,apci_groups_1,apci_groups_2,apci_groups_3,apci_groups_4,apci_groups_5,apci_groups_6
0,3.0,35.0,2.0,5.0,1.0,3.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,2.0,25.0,2.0,10.0,5.0,4.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,4.0,51.0,1.0,5.0,1.0,1.0,3.0,2.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,4.0,54.0,2.0,5.0,5.0,1.0,4.0,3.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,3.0,35.0,1.0,12.0,1.0,3.0,3.0,3.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [30]:
ds = ds.drop(['AgeHead','AgeGroup','SexHead', 'Mainlang','Mainsinc', 'Tenure','Urbrur', 'Attain','apci_groups'], axis=1)

In [31]:
ds.head()

,AgeGroup_0,AgeGroup_1,AgeGroup_2,AgeGroup_3,AgeGroup_4,AgeGroup_5,SexHead_0,SexHead_1,Mainlang_0,Mainlang_1,...,Attain_3,Attain_4,Attain_5,apci_groups_0,apci_groups_1,apci_groups_2,apci_groups_3,apci_groups_4,apci_groups_5,apci_groups_6
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [32]:
ds.to_csv('firsthotcol.csv')

In [47]:
ds1 = pd.read_csv('firsthotcol.csv', index_col=0)

In [48]:
ds1.head()

,AgeGroup_0,AgeGroup_1,AgeGroup_2,AgeGroup_3,AgeGroup_4,AgeGroup_5,SexHead_0,SexHead_1,Mainlang_0,Mainlang_1,...,Attain_3,Attain_4,Attain_5,apci_groups_0,apci_groups_1,apci_groups_2,apci_groups_3,apci_groups_4,apci_groups_5,apci_groups_6
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [49]:
ds1 = ds1.drop(['Tenure_0','Tenure_1','Tenure_2','Tenure_3','Tenure_4','Urbrur_0','Urbrur_1',\
              'Urbrur_2','Urbrur_3','Attain_0', 'Attain_1','Attain_2', 'Attain_3', 'Attain_4','Attain_5'], axis=1)

In [54]:
ds1.head()

,AgeGroup_0,AgeGroup_1,AgeGroup_2,AgeGroup_3,AgeGroup_4,AgeGroup_5,SexHead_0,SexHead_1,Mainlang_0,Mainlang_1,...,Mainsinc_5,Mainsinc_6,Mainsinc_7,apci_groups_0,apci_groups_1,apci_groups_2,apci_groups_3,apci_groups_4,apci_groups_5,apci_groups_6
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [55]:
X = ds1
Y = ds1.iloc[:, -7:].values

In [130]:
X

,AgeGroup_0,AgeGroup_1,AgeGroup_2,AgeGroup_3,AgeGroup_4,AgeGroup_5,SexHead_0,SexHead_1,Mainlang_0,Mainlang_1,...,Mainsinc_5,Mainsinc_6,Mainsinc_7,apci_groups_0,apci_groups_1,apci_groups_2,apci_groups_3,apci_groups_4,apci_groups_5,apci_groups_6
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
18,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
22,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
23,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
25,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10060,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10061,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10062,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10063,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10064,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10065,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10066,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10067,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10068,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10069,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10070,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10071,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10072,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10073,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10074,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10075,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10076,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10077,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10078,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10079,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10080,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10081,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10082,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10083,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10084,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10085,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10086,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10087,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10088,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10089,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [131]:
Y

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

## STEP 5 Train Test Split for Model Development

In [167]:
#Splitting the dataset into the Training set and the Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

## STEP 6 Import Modules for Model Development

In [168]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

## STEP 7 Initialize Sequential Model

In [169]:
#Initializing Neural Network
classifier = Sequential()

## STEP 8 Adding the layers one by one

In [170]:
# first input layer
classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu', input_dim = 36))

In [171]:
# hidden layer

classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu'))

In [172]:
# output layer

classifier.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'softmax'))

## STEP 9 Compiling the  Artificial Neural Network

In [173]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

## STEP 10 Fitting, predicting for the Model

In [174]:
# fitting the ann
classifier.fit(X_train, y_train, batch_size = 10, epochs = 25)

Epoch 1/25
8072/8072 [==============================] - 5s 622us/step - loss: 0.3554 - acc: 0.8588
Epoch 2/25
8072/8072 [==============================] - 3s 396us/step - loss: 0.2714 - acc: 0.8952
Epoch 3/25
8072/8072 [==============================] - 4s 440us/step - loss: 0.2311 - acc: 0.9008
Epoch 4/25
8072/8072 [==============================] - 3s 360us/step - loss: 0.2049 - acc: 0.9267
Epoch 5/25
8072/8072 [==============================] - 3s 400us/step - loss: 0.1857 - acc: 0.9267
Epoch 6/25
8072/8072 [==============================] - 3s 387us/step - loss: 0.1695 - acc: 0.9267
Epoch 7/25
8072/8072 [==============================] - 3s 399us/step - loss: 0.1541 - acc: 0.9470
Epoch 8/25
8072/8072 [==============================] - 3s 360us/step - loss: 0.1401 - acc: 0.9533
Epoch 9/25
8072/8072 [==============================] - 3s 377us/step - loss: 0.1279 - acc: 0.9648
Epoch 10/25
8072/8072 [==============================] - 3s 401us/step - loss: 0.1171 - acc: 0.9797
Epoch 11/25
8072/8072 [==============================] - 3s 359us/step - loss: 0.1074 - acc: 0.9799
Epoch 12/25
8072/8072 [==============================] - 3s 386us/step - loss: 0.0986 - acc: 0.9798
Epoch 13/25
8072/8072 [==============================] - 3s 365us/step - loss: 0.0908 - acc: 0.9798
Epoch 14/25
8072/8072 [==============================] - 3s 349us/step - loss: 0.0841 - acc: 0.9799
Epoch 15/25
8072/8072 [==============================] - 3s 359us/step - loss: 0.0781 - acc: 0.9799
Epoch 16/25
8072/8072 [==============================] - 3s 331us/step - loss: 0.0731 - acc: 0.9799
Epoch 17/25
8072/8072 [==============================] - 3s 363us/step - loss: 0.0688 - acc: 0.9799
Epoch 18/25
8072/8072 [==============================] - 2s 308us/step - loss: 0.0647 - acc: 0.9799
Epoch 19/25
8072/8072 [==============================] - 3s 367us/step - loss: 0.0613 - acc: 0.9799
Epoch 20/25
8072/8072 [==============================] - 3s 350us/step - loss: 0.0588 - acc: 0.9799
Epoch 21/25
8072/8072 [==============================] - 3s 341us/step - loss: 0.0559 - acc: 0.9799
Epoch 22/25
8072/8072 [==============================] - 3s 358us/step - loss: 0.0538 - acc: 0.9799
Epoch 23/25
8072/8072 [==============================] - 3s 364us/step - loss: 0.0517 - acc: 0.9799
Epoch 24/25
8072/8072 [==============================] - 3s 395us/step - loss: 0.0503 - acc: 0.9799
Epoch 25/25
8072/8072 [==============================] - 3s 364us/step - loss: 0.0484 - acc: 0.9799

In [175]:
# 
score = classifier.evaluate(X_test, y_test, verbose=0)
print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

Test Loss: 0.047649623703385074
Test Accuracy: 0.9801076155587868

In [127]:
# predicting and evaluating model
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

## STEP 11 Predicting test set result

In [128]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

## STEP 12 Evaluate model performance

In [129]:
# Confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))
print(cm)

[[361   0   0   0   0   0   0]
 [  0 445   0   0   0   0   0]
 [  0   0 559   0   0   0   0]
 [  0   0   0 382   0   0   0]
 [  0   0   0   0 141   0   0]
 [  0   0   0   0   0  77   0]
 [  0   0   0   0   0   0  53]]